name: Docker unstable release

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  ssr:
    name: Build SSR docker image
    runs-on: ubuntu-latest

    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Configure QEMU
        uses: docker/setup-qemu-action@v1

      - name: Configure Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            jellyfin/jellyfin-vue:unstable-ssr
            jellyfin/jellyfin-vue:unstable-ssr.${{ steps.date.outputs.date }}.${{ github.sha }}

  static:
    name: Build static docker image
    runs-on: ubuntu-latest

    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Configure QEMU
        uses: docker/setup-qemu-action@v1

      - name: Configure Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          file: 'Dockerfile.static'
          tags: |
            jellyfin/jellyfin-vue:unstable
            jellyfin/jellyfin-vue:unstable.${{ steps.date.outputs.date }}.${{ github.sha }}
