name: Docker stable release

on:
  release:
    types: |
      released
      prereleased

jobs:
  ssr:
    name: Build SSR docker image
    runs-on: ubuntu-latest

    steps:
      - name: Configure QEMU
        uses: docker/setup-qemu-action@v1

      - name: Configure Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push SSR stable
        if: github.event.release.released
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            jellyfin/jellyfin-vue:stable-ssr
            jellyfin/jellyfin-vue:stable-ssr-${{ env.GITHUB_REF }}

      - name: Build and push SSR candidate
        if: github.event.release.prereleased
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            jellyfin/jellyfin-vue:rc-ssr
            jellyfin/jellyfin-vue:rc-ssr-${{ env.GITHUB_REF }}

  static:
    name: Build static docker image
    runs-on: ubuntu-latest

    steps:
      - name: Configure QEMU
        uses: docker/setup-qemu-action@v1

      - name: Configure Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push static stable
        if: github.event.release.released
        uses: docker/build-push-action@v2
        with:
          push: true
          file: 'Dockerfile.static'
          tags: |
            jellyfin/jellyfin-vue:stable
            jellyfin/jellyfin-vue:stable-${{ env.GITHUB_REF }}
            jellyfin/jellyfin-vue:latest

      - name: Build and push static candidate
        if: github.event.release.prereleased
        uses: docker/build-push-action@v2
        with:
          push: true
          file: 'Dockerfile.static'
          tags: |
            jellyfin/jellyfin-vue:rc
            jellyfin/jellyfin-vue:rc-ssr-${{ env.GITHUB_REF }}
